<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite skipped="0" hostname="Rajats-MacBook-Air.local" name="suiteA.testAA" tests="1" failures="0" timestamp="2020-08-05T18:13:53 EDT" time="0.643" errors="0">
  <testcase name="AAtestAA" time="0.643" classname="suiteA.testAA"/>
=======
<testsuite skipped="1" hostname="Shivanis-MacBook-Pro.local" name="suiteA.testAA" tests="2" failures="0" timestamp="2020-08-05T18:26:27 EDT" time="0.091" errors="1">
  <testcase name="AAtestAA" time="0.000" classname="suiteA.testAA">
    <skipped/>
  </testcase> <!-- AAtestAA -->
  <testcase name="init" time="0.091" classname="suiteA.testAA">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.aventstack.extentreports.ReportObservable.lambda$0(ReportObservable.java:225)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.aventstack.extentreports.ReportObservable.saveTest(ReportObservable.java:225)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:248)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:261)
at suiteA.testAA.init(testAA.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:683)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:510)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- init -->
>>>>>>> dad426847fe861d6abd5f4d92feed9ca89c8dd20
</testsuite> <!-- suiteA.testAA -->
